{% set name = "iiboost" %}
{% set version = "0.2" %}
{% set sha256 = "0ecd906b453a6a278651e324352bd6f820b70aa4ca15fa42843bdb5c01ee7079" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/cbecker/iiboost/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

  patches:
    - cmath_fixes.diff
    - python3.diff

build:
  number: 0
  skip: True        # [win or np!=112]
  features:
    - vc14          # [win and py35]

requirements:
  build:
    - python
    - toolchain
    - gcc                   # [linux]
    - cmake
    - eigen
    - numpy x.x
    - itk       4.11.*
    - boost     1.63.*
  run:
    - libgcc                # [linux]
    - python
    - numpy x.x
    - itk       4.11.*
    - boost     1.63.*

test:
  imports:
    - iiboost

about:
  home: https://github.com/cbecker/iiboost
  license: GPL3
  license_file: LICENSE.txt
  summary: 'Learning Context Cues for Synapse Segmentation'

extra:
  recipe-maintainers:
    - bluescarni
