{% set version = "4.11.0" %}

package:
  name: itk
  version: {{ version }}

source:
  url: https://github.com/InsightSoftwareConsortium/ITK/archive/v{{ version }}.tar.gz
  sha256: a1857aa89f02efce3e091d102fbff7b2c53fe40c7f74580a47236bfd846c4e8b

build:
  number: 0
  skip: True  # [win and py<34]
  features:
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python                # [win]
    - vc 10                 # [win and py34]
    - vc 14                 # [win and py>=35]
    - toolchain
    - cmake
    - expat
    - hdf5 1.8.17|1.8.17.*
    - jpeg
    - libpng
    - libtiff
    - zlib
  run:
    - vc 10                     # [win and py34]
    - vc 14                     # [win and py>=35]
    - expat
    - hdf5 1.8.17|1.8.17.*
    - jpeg
    - libpng
    - libtiff
    - zlib

test:
  commands:
    - test -d $PREFIX/include/ITK*                        # [unix]
    - if not exist %LIBRARY_INC%\\include\\ITK* exit 1    # [win]

about:
  home: https://itk.org/
  license: Apache License 2.0
  license_file: LICENSE
  summary: 'Insight Segmentation and Registration Toolkit'

extra:
  recipe-maintainers:
    - bluescarni
